---
driver:
  name: dokken
  chef_version: latest
  privileged: true

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
  - name: centos75
    driver:
      image: centos:7.5.1804
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install lsof which systemd-sysv initscripts net-tools vim wget

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[nginx::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
